"""add missing columns to goals and notes

Revision ID: 407d9e28f2b9
Revises: 5b25bbed9ef7
Create Date: 2025-09-16 11:07:07.076280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407d9e28f2b9'
down_revision: Union[str, Sequence[str], None] = '5b25bbed9ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('goals', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('goals', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'goals', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('goals', 'type')
    op.drop_column('goals', 'target_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.alter_column('goals', 'progress',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('goals', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('goals', 'teacher_id')
    # ### end Alembic commands ###
