"""add type and target_date to goals

Revision ID: 6f824ab2b0ff
Revises: add_goal_id_to_notes
Create Date: 2025-09-18 16:26:28.239333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f824ab2b0ff'
down_revision: Union[str, Sequence[str], None] = 'add_goal_id_to_notes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('type', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('target_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target_date')
    op.drop_column('goals', 'type')
    # ### end Alembic commands ###
